apiVersion: v1
kind: ServiceAccount
metadata:
  name: snmptrapd
  namespace: service-telemetry
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: snmptrapd
  name: snmptrapd
  namespace: service-telemetry
spec:
  ports:
  - name: snmptrapd
    port: 6200
    protocol: UDP
    targetPort: 6200
  selector:
    app: snmptrapd
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snmptrapd
  namespace: service-telemetry
spec:
  selector:
    matchLabels:
      app: snmptrapd
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: snmptrapd
    spec:
      containers:
      - image: quay.io/lmadsen-redhat/snmptrapd:latest
        imagePullPolicy: Always
        name: snmptrapd
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: snmptrapd
      serviceAccountName: snmptrapd
      terminationGracePeriodSeconds: 30
